### ISSUE TITLE
How to configure harbor URL

### ISSUE THREAD

**Issue by jpacios** [container-registry/harbor-api-client#13]
Hi, It is not clear to me how to configure the harbor URL (not in localhost). Is that possible?

Thanks!

**Comment by Vad1mo** [comment]
sure

see https://github.com/container-registry/harbor-api-client/blob/master/src/harbor_client/configuration.py#L43

**Comment by Doruce** [comment]
@Vad1mo 

It doesn't work, it is still looking for local host :/ 

urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v2.0/projects/activity-timeline/robots (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcd59408280>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by Vad1mo** [comment]
can you share the code?

**Comment by Doruce** [comment]
@Vad1mo I was using a wrong python version, it's working now.
